spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/staby
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: -1

logging:
  level:
    com:
      example:
        multipart: trace

mybatis:
  mapper-locations: classpath:mapper/**/*.xml