spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/staby

logging:
  level:
    com:
      example:
        multipart: trace

mybatis:
  mapper-locations: classpath:mapper/**/*.xml